2025-03-03 13:41:05,828 INFO    MainThread:2784239 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-03 13:41:05,828 INFO    MainThread:2784239 [wandb_setup.py:_flush():67] Configure stats pid to 2784239
2025-03-03 13:41:05,829 INFO    MainThread:2784239 [wandb_setup.py:_flush():67] Loading settings from /home/mwahlin/.config/wandb/settings
2025-03-03 13:41:05,829 INFO    MainThread:2784239 [wandb_setup.py:_flush():67] Loading settings from /usr/terminus/data-xrm-01/stamplab/users/mwahlin/2025/trab_master/test_SR_CNN/wandb/settings
2025-03-03 13:41:05,830 INFO    MainThread:2784239 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-03 13:41:05,830 INFO    MainThread:2784239 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /usr/terminus/data-xrm-01/stamplab/users/mwahlin/2025/trab_master/test_SR_CNN/wandb/run-20250303_134105-7jkfzdpm/logs/debug.log
2025-03-03 13:41:05,830 INFO    MainThread:2784239 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /usr/terminus/data-xrm-01/stamplab/users/mwahlin/2025/trab_master/test_SR_CNN/wandb/run-20250303_134105-7jkfzdpm/logs/debug-internal.log
2025-03-03 13:41:05,830 INFO    MainThread:2784239 [wandb_init.py:init():761] calling init triggers
2025-03-03 13:41:05,830 INFO    MainThread:2784239 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'batch_size': 32, 'learning_rate': 0.001, 'num_epochs': 7, 'optimizer': 'Adam', 'architecture': 'SRCNN', 'dataset': 'CIFAR10-32', 'depth': 4, 'conv1_filters': 64, 'conv2_filters': 32, '_wandb': {}}
2025-03-03 13:41:05,831 INFO    MainThread:2784239 [wandb_init.py:init():784] starting backend
2025-03-03 13:41:05,831 INFO    MainThread:2784239 [wandb_init.py:init():788] sending inform_init request
2025-03-03 13:41:05,839 INFO    MainThread:2784239 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-03-03 13:41:05,839 INFO    MainThread:2784239 [wandb_init.py:init():803] backend started and connected
2025-03-03 13:41:05,842 INFO    MainThread:2784239 [wandb_init.py:init():896] updated telemetry
2025-03-03 13:41:05,858 INFO    MainThread:2784239 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-03-03 13:41:06,199 INFO    MainThread:2784239 [wandb_init.py:init():995] starting run threads in backend
2025-03-03 13:41:06,497 INFO    MainThread:2784239 [wandb_run.py:_console_start():2377] atexit reg
2025-03-03 13:41:06,497 INFO    MainThread:2784239 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-03-03 13:41:06,502 INFO    MainThread:2784239 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-03-03 13:41:06,502 INFO    MainThread:2784239 [wandb_run.py:_redirect():2317] Redirects installed.
2025-03-03 13:41:06,508 INFO    MainThread:2784239 [wandb_init.py:init():1037] run started, returning control to user process
2025-03-03 13:41:10,577 WARNING MsgRouterThr:2784239 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "/home/mwahlin/myterminus/mamba/envs/ML_env/lib/python3.10/site-packages/wandb/sdk/interface/router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
  File "/home/mwahlin/myterminus/mamba/envs/ML_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
  File "/home/mwahlin/myterminus/mamba/envs/ML_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 270, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mwahlin/myterminus/mamba/envs/ML_env/lib/python3.10/site-packages/wandb/sdk/interface/router.py", line 70, in message_loop
    msg = self._read_message()
  File "/home/mwahlin/myterminus/mamba/envs/ML_env/lib/python3.10/site-packages/wandb/sdk/interface/router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-03-03 13:41:10,580 INFO    MsgRouterThr:2784239 [mailbox.py:close():115] Closing mailbox, abandoning 1 handles.
