Files already downloaded and verified
Files already downloaded and verified
Traceback (most recent call last):
  File "/home/mwahlin/myterminus/2025/trab_master/test_SR_CNN/CNN_SR/ml_model_SR_CNN.py", line 175, in <module>
    train_model(model, train_loader, val_loader, DEVICE, NUM_EPOCHS)
  File "/home/mwahlin/myterminus/2025/trab_master/test_SR_CNN/CNN_SR/ml_model_SR_CNN.py", line 118, in train_model
    outputs = model(lr_images)
  File "/home/mwahlin/myterminus/mamba/envs/ML_env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/mwahlin/myterminus/mamba/envs/ML_env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/mwahlin/myterminus/2025/trab_master/test_SR_CNN/CNN_SR/ml_model_SR_CNN.py", line 50, in forward
    x = self.conv3(x)
  File "/home/mwahlin/myterminus/mamba/envs/ML_env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/mwahlin/myterminus/mamba/envs/ML_env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/mwahlin/myterminus/mamba/envs/ML_env/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 554, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/mwahlin/myterminus/mamba/envs/ML_env/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 549, in _conv_forward
    return F.conv2d(
RuntimeError: Given groups=1, weight of size [3, 32, 5, 5], expected input[32, 64, 32, 32] to have 32 channels, but got 64 channels instead
Traceback (most recent call last):
  File "/home/mwahlin/myterminus/2025/trab_master/test_SR_CNN/CNN_SR/ml_model_SR_CNN.py", line 175, in <module>
    train_model(model, train_loader, val_loader, DEVICE, NUM_EPOCHS)
  File "/home/mwahlin/myterminus/2025/trab_master/test_SR_CNN/CNN_SR/ml_model_SR_CNN.py", line 118, in train_model
    outputs = model(lr_images)
  File "/home/mwahlin/myterminus/mamba/envs/ML_env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/mwahlin/myterminus/mamba/envs/ML_env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/mwahlin/myterminus/2025/trab_master/test_SR_CNN/CNN_SR/ml_model_SR_CNN.py", line 50, in forward
    x = self.conv3(x)
  File "/home/mwahlin/myterminus/mamba/envs/ML_env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/mwahlin/myterminus/mamba/envs/ML_env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/mwahlin/myterminus/mamba/envs/ML_env/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 554, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/mwahlin/myterminus/mamba/envs/ML_env/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 549, in _conv_forward
    return F.conv2d(
RuntimeError: Given groups=1, weight of size [3, 32, 5, 5], expected input[32, 64, 32, 32] to have 32 channels, but got 64 channels instead
